version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: coverage
    versions:
    - "5.4"
  - dependency-name: gidgethub
    versions:
    - 5.0.0
  - dependency-name: aiohttp
    versions:
    - 3.7.3
